export const ERV_DESIGN_STATUSES = [
  'CREATED','DRAWING_UPLOADED','AI_EXTRACTION_RUNNING','AI_REVIEW_REQUIRED',
  'CORE_MODEL_READY','COMPLIANCE_RUNNING','CALCULATION_RUNNING',
  'EQUIPMENT_SELECTION_READY','BOM_READY','REVIEW_READY','APPROVED','REJECTED','FAILED'
] as const;
export type ErvDesignStatus = (typeof ERV_DESIGN_STATUSES)[number];
